// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxso_C7jp4tOyONjTDBDd9sW6w_RovxU',
    appId: '1:8920896657:web:d5ad084f947b70cf4a1b30',
    messagingSenderId: '8920896657',
    projectId: 'onlinics-5836e',
    authDomain: 'onlinics-5836e.firebaseapp.com',
    storageBucket: 'onlinics-5836e.appspot.com',
    measurementId: 'G-0NFRLFZ9N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNKMV5rHHw46_namzIA_H8dMwRgh-q90',
    appId: '1:8920896657:android:16489535fc4746f04a1b30',
    messagingSenderId: '8920896657',
    projectId: 'onlinics-5836e',
    storageBucket: 'onlinics-5836e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDyXYGsby5aXzyCE-DH3wQMECIxaW-Sg',
    appId: '1:8920896657:ios:f6749615d32ea1af4a1b30',
    messagingSenderId: '8920896657',
    projectId: 'onlinics-5836e',
    storageBucket: 'onlinics-5836e.appspot.com',
    iosClientId: '8920896657-1mfjq6c6sdi4lefp9l26m7hstlqmj0sg.apps.googleusercontent.com',
    iosBundleId: 'com.jemish54.onlinics',
  );
}
